import 'dart:convert';
import 'dart:io';

const upstreamCommit = '8b65feaba36ecc6d58d8aeef96cdc7c5a04381bc';
const expectedCommandCount = 893;

void main(List<String> arguments) {
  if (arguments.length != 1) {
    throw ArgumentError(
      'Usage: dart run tool/generate_pm3_command_inventory.dart '
      '<proxmark3/doc/commands.md>',
    );
  }

  final sourceFile = File(arguments.single).absolute;
  final upstreamRoot = sourceFile.parent.parent.path;
  final canonicalSourcePath = File(
    '$upstreamRoot/doc/commands.md',
  ).absolute.path;
  if (sourceFile.path != canonicalSourcePath) {
    throw StateError(
      'Expected canonical source $canonicalSourcePath, received '
      '${sourceFile.path}',
    );
  }
  final commitResult = Process.runSync('git', [
    '-C',
    upstreamRoot,
    'rev-parse',
    'HEAD',
  ]);
  final actualCommit = (commitResult.stdout as String).trim();
  if (commitResult.exitCode != 0 || actualCommit != upstreamCommit) {
    throw StateError(
      'Expected upstream commit $upstreamCommit, found '
      '${actualCommit.isEmpty ? 'unavailable' : actualCommit}',
    );
  }

  final source = sourceFile.readAsStringSync();
  final committedSourceResult = Process.runSync('git', [
    '-C',
    upstreamRoot,
    'show',
    'HEAD:doc/commands.md',
  ]);
  if (committedSourceResult.exitCode != 0 ||
      committedSourceResult.stdout != source) {
    throw StateError(
      'The upstream command dump differs from the audited commit',
    );
  }

  final rowPattern = RegExp(r'^\|`(.+?)\s*`\|([YN])\s*\|`(.*)`$');
  final commands = <String, ({String description, bool offline})>{};

  for (final row in const LineSplitter().convert(source)) {
    final match = rowPattern.firstMatch(row);
    if (match == null) continue;

    final command = match.group(1)!.trimRight();
    if (command == 'help' || command.endsWith(' help')) continue;

    commands[command] = (
      description: match.group(3)!,
      offline: match.group(2) == 'Y',
    );
  }

  final inventory = commands.entries.toList()
    ..sort((left, right) => left.key.compareTo(right.key));
  if (inventory.length != expectedCommandCount) {
    throw StateError(
      'Expected $expectedCommandCount commands, found ${inventory.length}',
    );
  }

  final output = StringBuffer()
    ..writeln(
      '// Generated by tool/generate_pm3_command_inventory.dart. '
      'Do not edit manually.',
    )
    ..writeln("const pm3UpstreamCommit = '$upstreamCommit';")
    ..writeln('const pm3CommandCount = $expectedCommandCount;')
    ..writeln()
    ..writeln('class Pm3CommandInventoryEntry {')
    ..writeln('  final String command;')
    ..writeln('  final bool offline;')
    ..writeln('  final String description;')
    ..writeln()
    ..writeln('  const Pm3CommandInventoryEntry(')
    ..writeln('    this.command,')
    ..writeln('    this.offline,')
    ..writeln('    this.description,')
    ..writeln('  );')
    ..writeln('}')
    ..writeln()
    ..writeln('// dart format off')
    ..writeln('const pm3CommandInventory = <Pm3CommandInventoryEntry>[');

  for (final entry in inventory) {
    output.writeln(
      '  Pm3CommandInventoryEntry(${_dartString(entry.key)}, '
      '${entry.value.offline}, ${_dartString(entry.value.description)}),',
    );
  }

  output
    ..writeln('];')
    ..writeln('// dart format on');
  File(
    'lib/helpers/pm3_command_inventory.dart',
  ).writeAsStringSync(output.toString());
}

String _dartString(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
